// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxqYtnnzovd53BfRPXPMA4vFCF1Kic0Ao',
    appId: '1:547646714637:web:008d307362d83717e2b644',
    messagingSenderId: '547646714637',
    projectId: 'testing-4327c',
    authDomain: 'testing-4327c.firebaseapp.com',
    storageBucket: 'testing-4327c.firebasestorage.app',
    measurementId: 'G-SQ0EYT17M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgoQVeQfO-lXI2Vl0leuCc2Dl8POP8Zv0',
    appId: '1:547646714637:android:793b8defe8bb4fc4e2b644',
    messagingSenderId: '547646714637',
    projectId: 'testing-4327c',
    storageBucket: 'testing-4327c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUB3zRxbqyS6jeOueyUBvA91T5hSYzGMg',
    appId: '1:547646714637:ios:e7c3b8a261a00d3fe2b644',
    messagingSenderId: '547646714637',
    projectId: 'testing-4327c',
    storageBucket: 'testing-4327c.firebasestorage.app',
    iosClientId: '547646714637-n1vqtdrcak1p8m1ntpsgh9teadplitct.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthBackendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUB3zRxbqyS6jeOueyUBvA91T5hSYzGMg',
    appId: '1:547646714637:ios:e7c3b8a261a00d3fe2b644',
    messagingSenderId: '547646714637',
    projectId: 'testing-4327c',
    storageBucket: 'testing-4327c.firebasestorage.app',
    iosClientId: '547646714637-n1vqtdrcak1p8m1ntpsgh9teadplitct.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthBackendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxqYtnnzovd53BfRPXPMA4vFCF1Kic0Ao',
    appId: '1:547646714637:web:00c607307235268fe2b644',
    messagingSenderId: '547646714637',
    projectId: 'testing-4327c',
    authDomain: 'testing-4327c.firebaseapp.com',
    storageBucket: 'testing-4327c.firebasestorage.app',
    measurementId: 'G-1MKZC4JM6P',
  );

}